--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DavyCraft648/PMServerUI
build-by-default: true
branches:
- master
projects:
  PMServerUI:
    path: ""
    model: virion
    type: library
...
